services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: always
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: employee_clock
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
